### ISSUE TITLE
Duplicate labels passed to formatter class aren't handled correctly

### ISSUE THREAD

**Issue by shannon-alliance** [Lightning-AI/lightning-flash#1278]
## 🐛 Bug

The CommaDelimitedMultiLabelTargetFormatter (and probably other formatter classes) incorrectly handles duplicate labels. This leads to an error later in training and makes the root cause of the error extremely difficult to debug. There is no issue when a valid list of labels is given however if a user error causes duplicate labels to be given the code does not provide useful feedback.

### To Reproduce

The bug can be reproduced by passing a list containing a duplicate label to the formatter class:
```
labels = ["cat", "dog", "cat"]
formatter = CommaDelimitedMultiLabelTargetFormatter(labels=labels)
for label in labels:
    print(formatter(label))
    
# [0, 0, 1]
# [0, 1, 0]
# [0, 0, 1]

print(formatter.labels)
# ['cat', 'dog', 'cat']
print(formatter.num_classes)
# 3    <-- No, there's really just 2, "cat" and "dog". It just happens that cat was given twice
print (repr(formatter.label_to_idx))
# {'cat': 2, 'dog': 1}   <-- this is correct
```
This leads to failures during training and an error that provides no real clue to the root cause:

#### Code sample

```
import torch

import flash
from flash.core.data.utilities.classification import CommaDelimitedMultiLabelTargetFormatter
from flash.text import TextClassificationData, TextClassifier


datamodule = TextClassificationData.from_lists(
    train_data=["likes yarn", "chases mice", "eats barf"],
    train_targets=["cat", "cat", "dog"],
    target_formatter=CommaDelimitedMultiLabelTargetFormatter(labels=["cat", "dog", "cat"]),  # note extra cat here
)
print(f"NUM CLASSES: {datamodule.num_classes}")
print(f"LABELS: {datamodule.labels}")

# 2. Build the task
model = TextClassifier(labels=datamodule.labels)

# 3. Create the trainer and finetune the model
trainer = flash.Trainer(max_epochs=3, gpus=torch.cuda.device_count())
trainer.finetune(model, datamodule=datamodule, strategy="freeze")
```

Results in:

```
NUM CLASSES: 3
LABELS: ['cat', 'dog', 'cat']
...
Traceback (most recent call last):
  File "/ml_server/text_classifier_test_2.py", line 30, in <module>
    trainer.finetune(model, datamodule=datamodule, strategy="freeze")
  File "/ml_server/.venv/lib/python3.9/site-packages/flash/core/trainer.py", line 161, in finetune
    return super().fit(model, train_dataloader, val_dataloaders, datamodule)
  File "/ml_server/.venv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 771, in fit
    self._call_and_handle_interrupt(
  File "/ml_server/.venv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 724, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/ml_server/.venv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 812, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/ml_server/.venv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1237, in _run
    results = self._run_stage()
  File "/ml_server/.venv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1324, in _run_stage
    return self._run_train()
  File "/ml_server/.venv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1354, in _run_train
    self.fit_loop.run()
  File "/ml_server/.venv/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/ml_server/.venv/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 269, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/ml_server/.venv/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/ml_server/.venv/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 208, in advance
    batch_output = self.batch_loop.run(batch, batch_idx)
  File "/ml_server/.venv/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/ml_server/.venv/lib/python3.9/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(split_batch, optimizers, batch_idx)
  File "/ml_server/.venv/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/ml_server/.venv/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 203, in advance
    result = self._run_optimization(
  File "/ml_server/.venv/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 256, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, batch_idx, closure)
  File "/ml_server/.venv/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 369, in _optimizer_step
    self.trainer._call_lightning_module_hook(
  File "/ml_server/.venv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1596, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/ml_server/.venv/lib/python3.9/site-packages/pytorch_lightning/core/lightning.py", line 1625, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/ml_server/.venv/lib/python3.9/site-packages/pytorch_lightning/core/optimizer.py", line 168, in step
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/ml_server/.venv/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 193, in optimizer_step
    return self.precision_plugin.optimizer_step(model, optimizer, opt_idx, closure, **kwargs)
  File "/ml_server/.venv/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 155, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "/ml_server/.venv/lib/python3.9/site-packages/torch/optim/optimizer.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/ml_server/.venv/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/ml_server/.venv/lib/python3.9/site-packages/torch/optim/adam.py", line 100, in step
    loss = closure()
  File "/ml_server/.venv/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 140, in _wrap_closure
    closure_result = closure()
  File "/ml_server/.venv/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 148, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/ml_server/.venv/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 134, in closure
    step_output = self._step_fn()
  File "/ml_server/.venv/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 427, in _training_step
    training_step_output = self.trainer._call_strategy_hook("training_step", *step_kwargs.values())
  File "/ml_server/.venv/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1766, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/ml_server/.venv/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 333, in training_step
    return self.model.training_step(*args, **kwargs)
  File "/ml_server/.venv/lib/python3.9/site-packages/flash/core/model.py", line 403, in training_step
    output = self.step(batch, batch_idx, self.train_metrics)
  File "/ml_server/.venv/lib/python3.9/site-packages/flash/text/classification/model.py", line 122, in step
    return super().step(batch, batch_idx, metrics)
  File "/ml_server/.venv/lib/python3.9/site-packages/flash/core/model.py", line 353, in step
    losses = {name: l_fn(y_hat, y) for name, l_fn in self.loss_fn.items()}
  File "/ml_server/.venv/lib/python3.9/site-packages/flash/core/model.py", line 353, in <dictcomp>
    losses = {name: l_fn(y_hat, y) for name, l_fn in self.loss_fn.items()}
  File "/ml_server/.venv/lib/python3.9/site-packages/torch/nn/functional.py", line 2996, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: Expected floating point type for target with class probabilities, got Long
```

### Expected behavior

I'm not sure what the right behavior should be here, probably one of:

a.) Throw an error warning of the duplicate label(s) in the DataLoader or Formatter class
b.) Silently drop duplicate classes and make formatter.num_classes return the number of UNIQUE labels
c.) Handle or ignore duplicate labels in the training / optimiser classes
d.) Throw an error during training but make it a BETTER error, that helps clarify root cause is duplicate labels

Really depends on whether there are any scenarios where having duplicate labels makes sense (I don't see how but I'm not an ML expert).

### Environment

 - OS: Linux
 - Python version: 3.9
 - PyTorch/Lightning/Flash Version: 1.11.0 / 1.6.0 / 0.7.2
 - GPU models and configuration: AWS cloud "Persistence M" (Driver Version: 510.47.03    CUDA Version: 11.6 )

**Comment by ethanwharris** [comment]
Hi @shannon-alliance thanks for reporting this! Definitely agree that we should treat the labels as a set or check for uniqueness. Although in this case the error you are getting is because you need to pass `multi_label = True` when creating the `TextClassifier`. E.g. this is working for me:
```python
import torch

import flash
from flash.core.data.utilities.classification import CommaDelimitedMultiLabelTargetFormatter
from flash.text import TextClassificationData, TextClassifier


datamodule = TextClassificationData.from_lists(
    train_data=["likes yarn", "chases mice", "eats barf"],
    train_targets=["cat", "cat", "dog"],
    target_formatter=CommaDelimitedMultiLabelTargetFormatter(labels=["cat", "dog", "cat"]),
    batch_size=1,
)
print(f"NUM CLASSES: {datamodule.num_classes}")
print(f"LABELS: {datamodule.labels}")

# 2. Build the task
model = TextClassifier(multi_label=datamodule.multi_label, labels=datamodule.labels)

# 3. Create the trainer and finetune the model
trainer = flash.Trainer(max_epochs=3, gpus=torch.cuda.device_count())
trainer.finetune(model, datamodule=datamodule, strategy="freeze")
```

**Comment by shannon-alliance** [comment]
@ethanwharris You're right. Huge thanks for the clarification. When I was testing the minimal code I may have accidentely made the datamodule a single-label classification and confused myself. I didn't know about the multi_label argument to TextClassifier so it would have taken me ages to solve.
