### ISSUE TITLE
Error while running simclr for cifar10 on lightning flash

### ISSUE THREAD

**Issue by ammarlam10** [Lightning-AI/lightning-flash#1401]
Im trying to run simclr using ImageEmbedder but getting this error, my code is attached below

```
Traceback (most recent call last):
  File "/workspace/DATA/ADL/simclrcifar10.py", line 300, in <module>
    trainer.fit(embedder, datamodule=datamodule)
  File "/home/ra49bid2/miniconda3/lib/python3.9/site-packages/flash/core/trainer.py", line 120, in fit
    return super().fit(model, train_dataloader, val_dataloaders, datamodule)
  File "/home/ra49bid2/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "/home/ra49bid2/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt
    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
  File "/home/ra49bid2/miniconda3/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/spawn.py", line 78, in launch
    mp.spawn(
  File "/home/ra49bid2/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/ra49bid2/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 189, in start_processes
    process.start()
  File "/home/ra49bid2/miniconda3/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/ra49bid2/miniconda3/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/ra49bid2/miniconda3/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/ra49bid2/miniconda3/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/ra49bid2/miniconda3/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/ra49bid2/miniconda3/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: args[0] from __newobj__ args has the wrong class


```

**Comment by ammarlam10** [comment]
The code
`
import torch
from torchvision.datasets import CIFAR10
from pytorch_lightning.callbacks import LearningRateMonitor

from pytorch_lightning.callbacks import TQDMProgressBar


import flash
from flash.core.data.utils import download_data
from flash.image import ImageClassificationData, ImageEmbedder

datamodule = ImageClassificationData.from_datasets(
    train_dataset=CIFAR10("/workspace/DATA", download=False),
    batch_size=8,
)

embedder = ImageEmbedder(
    backbone="resnet",
    training_strategy="simclr",
    head="simclr_head",
    pretraining_transform="simclr_transform",
    training_strategy_kwargs={"latent_embedding_dim": 128},
    pretraining_transform_kwargs={"size_crops": [32]},
)

trainer = flash.Trainer(max_epochs=1, gpus=1,
    callbacks=[LearningRateMonitor(logging_interval="step"), TQDMProgressBar(refresh_rate=10)])
trainer.fit(embedder, datamodule=datamodule)`

**Comment by ammarlam10** [comment]
I was able to solve it by changing trainer strategy to ddp
