### ISSUE TITLE
error when using  LightningDataModule with flash.image.ImageEmbedder

### ISSUE THREAD

**Issue by ammarlam10** [Lightning-AI/lightning-flash#1402]
`Traceback (most recent call last):
  File "/workspace/DATA/ADL/simclrdrac.py", line 127, in <module>
    trainer.fit(embedder, datamodule=datamodule)
  File "/home/ra49bid2/miniconda3/lib/python3.9/site-packages/flash/core/trainer.py", line 120, in fit
    return super().fit(model, train_dataloader, val_dataloaders, datamodule)
  File "/home/ra49bid2/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "/home/ra49bid2/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/ra49bid2/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/ra49bid2/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1236, in _run
    results = self._run_stage()
  File "/home/ra49bid2/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1323, in _run_stage
    return self._run_train()
  File "/home/ra49bid2/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1345, in _run_train
    self._run_sanity_check()
  File "/home/ra49bid2/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1413, in _run_sanity_check
    val_loop.run()
  File "/home/ra49bid2/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/ra49bid2/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/ra49bid2/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/ra49bid2/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 128, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/ra49bid2/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 226, in _evaluation_step
    output = self.trainer._call_strategy_hook("validation_step", *kwargs.values())
  File "/home/ra49bid2/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1765, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/ra49bid2/miniconda3/lib/python3.9/site-packages/pytorch_lightning/strategies/ddp.py", line 355, in validation_step
    return self.model(*args, **kwargs)
  File "/home/ra49bid2/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ra49bid2/miniconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1008, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/ra49bid2/miniconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 969, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/ra49bid2/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ra49bid2/miniconda3/lib/python3.9/site-packages/pytorch_lightning/overrides/base.py", line 93, in forward
    return self.module.validation_step(*inputs, **kwargs)
  File "/home/ra49bid2/miniconda3/lib/python3.9/site-packages/flash/core/adapter.py", line 112, in validation_step
    return self.adapter.validation_step(batch, batch_idx)
  File "/home/ra49bid2/miniconda3/lib/python3.9/site-packages/flash/image/embedding/vissl/adapter.py", line 206, in validation_step
    loss = self.shared_step(batch, train=False)
  File "/home/ra49bid2/miniconda3/lib/python3.9/site-packages/flash/image/embedding/vissl/adapter.py", line 183, in shared_step
    out = self.ssl_forward(batch[DataKeys.INPUT])
TypeError: list indices must be integers or slices, not DataKeys
`

I'm getting the above error when I use custom lightning datamodule with trainer.fit()

**Comment by ammarlam10** [comment]
```
class DRACDataModule(pl.LightningDataModule):
    def __init__(self, data_dir: str = "./", transformer: str = "./",batch_size=64):
        super().__init__()
        self.data_dir = data_dir
        self.transform = transformer
        self.batch_size = batch_size
       
    def prepare_data(self):
        print('already downloaded')
        # download

    def setup(self, stage = None):

        if stage == "fit" or stage is None:
            data_full = datasets.ImageFolder(root=self.data_dir,transform=self.transform)
            self.data_train, self.data_val = random_split(data_full, [511, 100])

        if stage == "test" or stage is None:
            self.data_test = datasets.ImageFolder(root=self.data_dir,transform=self.transform)

        if stage == "predict" or stage is None:
            self.data_predict = datasets.ImageFolder(root=self.data_dir,transform=self.transform)

    def train_dataloader(self):
        return DataLoader(self.data_train, batch_size=self.batch_size , num_workers=8)

    def val_dataloader(self):
        return DataLoader(self.data_val, batch_size=self.batch_size, num_workers=8)

    def test_dataloader(self):
         return DataLoader(self.data_test, batch_size=self.batch_size, num_workers=8)

    def predict_dataloader(self):
         return DataLoader(self.data_predict, batch_size=self.batch_size, num_workers=8)


data_transform = transforms.Compose([
        transforms.RandomCrop(512),
         transforms.RandomHorizontalFlip(),
        transforms.ToTensor()
    ])


datamodule = DRACDataModule(data_dir='/workspace/DATA/C. Diabetic Retinopathy Grading', transformer=data_transform)


embedder = ImageEmbedder(
    backbone="resnet",
    training_strategy="simclr",
    head="simclr_head",
    pretraining_transform="simclr_transform",
    training_strategy_kwargs={"latent_embedding_dim": 128},
    pretraining_transform_kwargs={"size_crops": [32]},
)

trainer = flash.Trainer(strategy='ddp',max_epochs=1, gpus=1,
    callbacks=[LearningRateMonitor(logging_interval="step"), TQDMProgressBar(refresh_rate=10)])

trainer.fit(embedder, datamodule=datamodule)


```

**Comment by ammarlam10** [comment]
similar to #637, found the solution there
